### ISSUE TITLE
Can not download maestro

### ISSUE THREAD

**Issue by JianGuoZhou3** [liulab-dfci/MAESTRO#149]
````
(MAESTRO) [zhou@localhost ~]$ conda install maestro=1.5.1 -c liulab-dfci
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
````

**Comment by jianguozhouzunyimedicaluniversity** [comment]
````
(base) [zhou@localhost ~]$ mamba create -n MAESTRO maestro=1.5.1 -c liulab-dfci


                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        Supported by @QuantStack

        GitHub:  https://github.com/QuantStack/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████

Getting  liulab-dfci linux-64
Getting  liulab-dfci noarch
Getting  Getting  anaconda/cloud/bioconda noarchGetting 
 anaconda/cloud/conda-forge linux-64
anaconda/cloud/bioconda linux-64Getting  anaconda/cloud/conda-forge noarch

Getting  Getting  anaconda/pkgs/msys2 anaconda/pkgs/msys2 noarchlinux-64

Getting  anaconda/pkgs/pro linux-64
Getting  anaconda/pkgs/pro noarch
Getting  Getting  anaconda/pkgs/r noarch
anaconda/pkgs/r linux-64
Getting  anaconda/pkgs/free linux-64
Getting  anaconda/pkgs/free noarch
Getting  anaconda/pkgs/main linux-64
Getting  anaconda/pkgs/main noarch
Getting  pkgs/main linux-64
Getting  pkgs/main noarch
Getting  pkgs/r linux-64
Getting  pkgs/r Getting  conda-forge linux-64noarch

Getting  conda-forge noarch
Getting  knights-lab linux-64
Getting  knights-lab noarch

Looking for: [u'maestro 1.5.1.*']

76483 packages in https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
0 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/noarch
33790 packages in https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/noarch
0 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/linux-64
230428 packages in https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64
815 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/pro/linux-64
39959 packages in https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/linux-64
0 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/pro/noarch
230436 packages in https://conda.anaconda.org/conda-forge/linux-64
5025 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
29 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/noarch
76550 packages in https://conda.anaconda.org/conda-forge/noarch
23625 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
4526 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
13330 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/linux-64
6637 packages in https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
4526 packages in https://repo.anaconda.com/pkgs/main/noarch
23625 packages in https://repo.anaconda.com/pkgs/main/linux-64
5025 packages in https://repo.anaconda.com/pkgs/r/noarch
6637 packages in https://repo.anaconda.com/pkgs/r/linux-64
31 packages in https://conda.anaconda.org/liulab-dfci/linux-64
0 packages in https://conda.anaconda.org/liulab-dfci/noarch
1 packages in https://conda.anaconda.org/knights-lab/noarch
12 packages in https://conda.anaconda.org/knights-lab/linux-64

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/zhou/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/zhou/miniconda2/lib/python2.7/site-packages/mamba/mamba.py", line 522, in exception_converter
        raise e
    RuntimeError: Did not find key as expected!

`$ /home/zhou/miniconda2/bin/mamba create -n MAESTRO maestro=1.5.1 -c liulab-dfci`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/home/zhou/miniconda2:/home/zhou/miniconda2/x86_64-conda-linux-
                          gnu/sysroot/usr
      CONDA_BUILD_SYSROOT=/home/zhou/miniconda2/x86_64-conda-linux-gnu/sysroot
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/zhou/miniconda2/bin/conda
             CONDA_PREFIX=/home/zhou/miniconda2
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/zhou/miniconda2/bin/python
               CONDA_ROOT=/home/zhou/miniconda2
              CONDA_SHLVL=1
    CONDA_TOOLCHAIN_BUILD=x86_64-conda-linux-gnu
     CONDA_TOOLCHAIN_HOST=x86_64-conda-linux-gnu
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/lib64/R/lib::/lib:/usr/local/lib64:/usr/lib/jvm/java-1.8.0-
                          openjdk-1.8.0.262.b10-0.el7_8.x86_64/jre/lib/amd64/server
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                     PATH=/home/zhou/.aspera/connect/bin:/home/zhou/soft/sratoolkit.2.9.6-1-cent
                          os_linux64/bin/:/home/zhou/soft/sratoolkit.2.9.6-1-centos_linux64/bin/
                          :/home/zhou/soft/sratoolkit.2.9.6-1-centos_linux64/bin/:/home/zhou/.as
                          pera/connect/bin:/home/zhou/soft/sratoolkit.2.9.6-1-centos_linux64/bin
                          /:/soft/sratoolkit.2.10.8-centos_linux64/bin/:/soft/sratoolkit.2.9.6-1
                          -centos_linux64/bin/:/soft/sratoolkit.2.9.6-1-centos_linux64/bin/:/sof
                          t/sratoolkit.2.9.6-1-centos_linux64/bin/:/soft/sratoolkit.2.9.6-1-cent
                          os_linux64/bin/:/soft/sratoolkit.2.10.8-centos_linux64/bin/:/soft/srat
                          oolkit.2.10.8-centos_linux64/bin/:/soft/sratoolkit.2.10.8-centos_linux
                          64/bin/:/soft/sratoolkit.2.10.8-centos_linux64/bin/:/soft/sratoolkit.2
                          .10.8-centos_linux64/bin/:/soft/sratoolkit.2.10.8-centos_linux64/bin/:
                          /soft/sratoolkit.2.10.8-centos_linux64/bin/:/soft/sratoolkit.2.10.8-ce
                          ntos_linux64/bin/:/soft/sratoolkit.2.10.8-centos_linux64/bin/:/soft/sr
                          atoolkit.2.10.8-centos_linux64/bin/:/soft/sratoolkit.2.9.6-1-centos_li
                          nux64/bin/:/home/zhou/.aspera/connect/bin:/opt/MegaRAID/MegaCli/:/home
                          /zhou/miniconda2/bin:/home/zhou/miniconda2/condabin:/usr/local/sbin:/u
                          sr/local/bin:/usr/sbin:/usr/bin:/usr/lib/rstudio-
                          server/bin/postback:/usr/bin:/home/zhou/.local/bin:/home/zhou/bin
       REQUESTS_CA_BUNDLE=<not set>
   RMARKDOWN_MATHJAX_PATH=/usr/lib/rstudio-server/resources/mathjax-27
        RS_RPOSTBACK_PATH=/usr/lib/rstudio-server/bin/rpostback
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/zhou/miniconda2
            shell level : 1
       user config file : /home/zhou/.condarc
 populated config files : /home/zhou/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 2.7.18.final.0
       virtual packages : __glibc=2.17
       base environment : /home/zhou/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/liulab-dfci/linux-64
                          https://conda.anaconda.org/liulab-dfci/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/pro/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/knights-lab/linux-64
                          https://conda.anaconda.org/knights-lab/noarch
          package cache : /home/zhou/miniconda2/pkgs
                          /home/zhou/.conda/pkgs
       envs directories : /home/zhou/miniconda2/envs
                          /home/zhou/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.25.1 CPython/2.7.18 Linux/3.10.0-1127.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
````

**Comment by JianGuoZhou3** [comment]
Now it's worked.

````
conda create -n MAESTRO python=3.8 -y
conda install maestro=1.5.1 -c liulab-dfci
````
