### ISSUE TITLE
ImportError: cannot import name typeDict

### ISSUE THREAD

**Issue by KunFang93** [liulab-dfci/MAESTRO#166]
Hi,

Thanks for providing this useful tool! I tried to run tutorial but with the following error
```
MAESTRO scrna-init --platform 10x-genomics --species GRCh38 --cores 8 --rseqc --directory pbmc_1k_v3_fastqs --count-cutoff 1000 --gene-cutoff 500 --cell-cutoff 10 --mapindex /scratch/u/kfang/Software/MAESTRO/references/scRNA/Refdata_scRNA_MAESTRO_GRCh38_1.2.2/GRCh38_STAR_2.7.6a --whitelist /scratch/u/kfang/Software/MAESTRO/references/whitelist/3M-february-2018.txt --barcode-start 1 --barcode-length 16 --umi-start 17 --umi-length 12 --lisadir /scratch/u/kfang/Software/MAESTRO/references/annotation/hg38_1000_2.0.h5 --signature human.immune.CIBERSORT
Traceback (most recent call last):
  File "/home/kfang/miniconda3/envs/MAESTRO/bin/MAESTRO", line 4, in <module>
    __import__('pkg_resources').run_script('MAESTRO==1.5.1', 'MAESTRO')
  File "/home/kfang/miniconda3/envs/MAESTRO/lib/python3.8/site-packages/pkg_resources/__init__.py", line 720, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kfang/miniconda3/envs/MAESTRO/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1559, in run_script
    exec(code, namespace, namespace)
  File "/home/kfang/miniconda3/envs/MAESTRO/lib/python3.8/site-packages/MAESTRO-1.5.1-py3.8.egg-info/scripts/MAESTRO", line 17, in <module>
    from MAESTRO.scATAC_H5Process import *
  File "/home/kfang/miniconda3/envs/MAESTRO/lib/python3.8/site-packages/MAESTRO/scATAC_H5Process.py", line 11, in <module>
    import tables
  File "/home/kfang/miniconda3/envs/MAESTRO/lib/python3.8/site-packages/tables/__init__.py", line 24, in <module>
    from .utilsextension import (
  File "tables/utilsextension.pyx", line 169, in init tables.utilsextension
ImportError: cannot import name typeDict
```

I wondered how I could solve this? 

Best,
Kun

**Comment by jaymahat** [comment]
same problem. any suggestions?

**Comment by yanw3** [comment]
Looking for the suggestions for the same problem.

**Comment by mourisl** [comment]
It seems this is probably a version issue in the package "tables". Could you please start a python3 session in MAESTRO conda environment, and run "import tables" to see whether it works? If it fails, is it possible to change the package tables version to 3.7.0 or 3.6.1?

**Comment by wangjk321** [comment]
`pip install tables==3.7.0`
`pip install numpy==1.21`

May fix the bug
