### ISSUE TITLE
Python scripts should use argparse

### ISSUE THREAD

**Issue by ctokheim** [liulab-dfci/MAESTRO#18]
Scripts like scRNA_qc.py use many positional arguments, which is not particularly user friendly if the user needs to run the script outside of the snakemake pipeline. It would be easier for the user if argparse was used so that they can specify command line flags and have a help doc for the script.

**Comment by taoliu** [comment]
@ctokheim Thank you for the suggestion! We will definitely work on this!

**Comment by chenfeiwang** [comment]
Thank you Collin! In the latest version of MAESTRO, we have added detailed argparse for subfunctions of MAESTRO, please update and check the newest tutorials for this.

**Comment by taoliu** [comment]
@chenfeiwang Could you add 'required' arguments to each of the sub-command in MAESTRO?  Without 'required' arguments, users will get:

```
$MAESTRO scatac-peakcount
Traceback (most recent call last):
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/bin/MAESTRO", line 4, in <module>
    __import__('pkg_resources').run_script('MAESTRO==1.1.0', 'MAESTRO')
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/lib/python3.7/site-packages/MAESTRO-1.1.0-py3.7.egg-info/scripts/MAESTRO", line 92, in <module>
    main()
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/lib/python3.7/site-packages/MAESTRO-1.1.0-py3.7.egg-info/scripts/MAESTRO", line 79, in main
    peakcount(directory = args.directory, outprefix = args.outprefix, peak = args.peak, fragment = args.fragment, barcode = args.barcode, count_cutoff = args.count_cutoff, cores = args.cores, species = args.species)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/lib/python3.7/site-packages/MAESTRO/scATAC_10x_PeakCount.py", line 172, in peakcount
    barcode_list = filter_fragment_file(barcode, fragment, count_cutoff)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO110/lib/python3.7/site-packages/MAESTRO/scATAC_10x_PeakCount.py", line 70, in filter_fragment_file
    for line in open(frag_file, 'r'):
FileNotFoundError: [Errno 2] No such file or directory: ''
```
In the above case, I believe `--peak`,  `--fragment`, and `--barcode` are required. Please add `required=True` to the `add_argument` function.
