### ISSUE TITLE
error at scatac_qcfilter step

### ISSUE THREAD

**Issue by yzz207** [liulab-dfci/MAESTRO#56]
Hi,
I got the error below when running the pipeline starting from bam. Any suggestion what I should try to fix this? Also I wonder if the pipeline can be started at any point. In my case here, I would like to resume the pipeline from this scatac_qcfilter step once I figure out the problem, rather than starting over the whole pipeline again.  

rule scatac_qcfilter:
    input: Result/Analysis/SI_25417_peak_count.h5
    output: Result/QC/SI_25417_filtered_peak_count.h5
    jobid: 4
    benchmark: Result/Benchmark/SI_25417_QCFilter.benchmark

Traceback (most recent call last):
  File "/root/miniconda3/envs/MAESTRO/bin/MAESTRO", line 4, in <module>
    __import__('pkg_resources').run_script('MAESTRO==1.2.1', 'MAESTRO')
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO-1.2.1-py3.7.egg-info/scripts/MAESTRO", line 112, in <module>
    main()
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO-1.2.1-py3.7.egg-info/scripts/MAESTRO", line 94, in main
    scatac_qc(directory = args.directory, outprefix = args.outprefix, fileformat = args.format, peakcount = args.peakcount, feature = args.feature, barcode = args.barcode, single_stat = args.single_stat, peak_cutoff = args.peak_cutoff, count_cutoff = args.count_cutoff, frip_cutoff = args.frip_cutoff, cell_cutoff = args.cell_cutoff, species = args.species)
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO/scATAC_QC.py", line 147, in scatac_qc
    Filter(rawmatrix = peakmatrix, feature = features, barcode = barcodes, peak_cutoff = peak_cutoff, cell_cutoff = cell_cutoff, validcell = validcells_list, outprefix = filename, species = species)
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO/scATAC_QC.py", line 84, in Filter
    passed_cell_matrix = rawmatrix[np.ix_(passed_peak.tolist()[0], passed_cell.tolist()[0])]
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/scipy/sparse/_index.py", line 75, in __getitem__
    return self._get_arrayXarray(row, col)
  File "/root/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 665, in _get_arrayXarray
    major.size, major.ravel(), minor.ravel(), val)
ValueError: could not convert integer scalar
[Wed Sep  2 20:52:51 2020]
Error in rule scatac_qcfilter:
    jobid: 4
    output: Result/QC/SI_25417_filtered_peak_count.h5
    shell:
        MAESTRO scatac-qc --format h5 --peakcount Result/Analysis/SI_25417_peak_count.h5 --peak-cutoff 100 --cell-cutoff 10 --directory Result/QC --outprefix SI_25417
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Thanks,
Yuping

**Comment by yzz207** [comment]
Just to update. I set more stringent cutoffs for -count-cutoff and --frip-cutoff and it completed successfully.

**Comment by crazyhottommy** [comment]
good to know!
