### ISSUE TITLE
Bug: Missing default value or required status for `MAESTRO init` command

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#8]
The main executable script [MAESTRO](https://github.com/liulab-dfci/MAESTRO/blob/master/MAESTRO/MAESTRO) will throw exceptions when no argument is set for `init` command:

```
$ MAESTRO init 
Traceback (most recent call last):
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/bin/MAESTRO", line 4, in <module>
    __import__('pkg_resources').run_script('MAESTRO==1.0.1', 'MAESTRO')
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO-1.0.1-py3.7.egg-info/scripts/MAESTRO", line 79, in <module>
    main()
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO-1.0.1-py3.7.egg-info/scripts/MAESTRO", line 72, in main
    init_workflow(args.directory, args.module)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/site-packages/MAESTRO-1.0.1-py3.7.egg-info/scripts/MAESTRO", line 21, in init_workflow
    os.makedirs(directory)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/os.py", line 206, in makedirs
    head, tail = path.split(name)
  File "/mnt/lustre/users/tliu/miniconda3/envs/MAESTRO/lib/python3.7/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The solution is either to add `required=True` for `"-m"` and `"-d"`, or to set `default=` for these options.

https://github.com/liulab-dfci/MAESTRO/blob/1eba0a239fc38bf0687f4b66c9f5c5af07d89e74/MAESTRO/MAESTRO#L61-L62

**Comment by chenfeiwang** [comment]
Those bugs are corrected.
